import React, { useMemo, useState } from 'react';
import { IndianRupee, MapPin, Search, FileText, CheckCircle2 } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { LeafletGisMap } from '../gis/LeafletGisMap';
import { Modal } from '../layout/Modal';

const currency = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);

export const FinancialProjectWorkspace: React.FC = () => {
  const { activeProject, parcels, compensationRecords, documents, navigateToParcelInGis, setCurrentPage } = useApp();
  const [search, setSearch] = useState('');
  const [calculated, setCalculated] = useState(false);
  const [confirming, setConfirming] = useState(false);
  const [approved, setApproved] = useState(false);
  if (!activeProject) return null;
  const projectParcels = parcels.filter(parcel => parcel.projectId === activeProject.id);
  const projectRecords = compensationRecords.filter(record => record.projectId === activeProject.id);
  const projectDocuments = documents.filter(document => document.projectId === activeProject.id);
  const matchingRecords = projectRecords.filter(record => `${record.ownerBeneficiary} ${record.surveyNumber} ${record.khataNumber}`.toLowerCase().includes(search.toLowerCase()));
  const total = matchingRecords.reduce((sum, record) => sum + (calculated ? record.assessedAmount : record.approvedAmount || record.assessedAmount), 0);
  const paid = matchingRecords.reduce((sum, record) => sum + record.paidAmount, 0);
  const canCalculate = projectRecords.length > 0;
  return <div className="page-body">
    <div className="page-header-row"><div><h1 className="page-title">Financial Compensation Review</h1><p className="page-subtitle">{activeProject.name} · {activeProject.code} · Project stage: {activeProject.currentStage}</p></div><div style={{ display: 'flex', gap: 8 }}><button className="gov-btn gov-btn-secondary" onClick={() => setCurrentPage('projects')}>Back to Projects</button><button className="gov-btn gov-btn-primary" disabled={!canCalculate} onClick={() => setCalculated(true)}><IndianRupee size={15} /> Calculate Compensation</button></div></div>
    <div className="kpi-grid"><div className="metric-card"><span className="metric-card-label">Affected Landowners</span><strong className="metric-card-value">{projectRecords.length}</strong></div><div className="metric-card"><span className="metric-card-label">Affected Parcels</span><strong className="metric-card-value">{projectParcels.length || activeProject.villagesCount}</strong></div><div className="metric-card"><span className="metric-card-label">Land Acquired</span><strong className="metric-card-value">{activeProject.landAcquiredAcres} ac</strong></div><div className="metric-card"><span className="metric-card-label">Compensation Assessed</span><strong className="metric-card-value">{currency(total)}</strong></div></div>
    <div className="dashboard-mid-grid"><div className="gov-card gis-preview-card"><div className="gov-card-header"><div className="gov-card-title"><MapPin size={16} /><span>Project Parcels & Alignment</span></div></div><div className="gis-preview-map-box"><LeafletGisMap parcels={projectParcels} selectedParcelId={null} onSelectParcel={navigateToParcelInGis} height="300px" showLegend={false} showLayerToggle={false} /></div></div><div className="gov-card"><div className="gov-card-header"><div className="gov-card-title"><FileText size={16} /><span>Relevant Documents</span></div></div>{projectDocuments.length ? <div className="alert-feed">{projectDocuments.slice(0, 5).map(document => <div className="alert-item Information" key={document.id}><div className="alert-item-content"><div className="alert-item-title">{document.documentName}</div><div className="alert-item-sub">{document.category} · {document.status}</div></div></div>)}</div> : <p style={{ padding: 16, fontSize: 12, color: 'var(--gov-slate-500)' }}>No project documents are available from the current data source.</p>}</div></div>
    <div className="gov-card"><div className="gov-card-header"><div className="gov-card-title"><IndianRupee size={16} /><span>Affected Landowners & Compensation</span></div><div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><Search size={14} /><input className="gov-input" placeholder="Search owner, survey or khata" value={search} onChange={event => setSearch(event.target.value)} /></div></div><div className="table-container"><table className="gov-table"><thead><tr><th>Landowner / Survey</th><th>Hissa</th><th>Location</th><th style={{ textAlign: 'right' }}>Acquired area</th><th>Calculation</th><th style={{ textAlign: 'right' }}>Compensation</th><th>Payment status</th></tr></thead><tbody>{matchingRecords.map(record => { const parcel = projectParcels.find(item => item.surveyNumber === record.surveyNumber); const area = parcel?.areaAcres; const rate = parcel?.marketRatePerAcre; const assessed = calculated ? record.assessedAmount : record.approvedAmount || record.assessedAmount; return <tr key={record.id}><td><strong>{record.ownerBeneficiary}</strong><div className="project-table-code">Survey No. {record.surveyNumber} · Khata {record.khataNumber}</div></td><td>Not available</td><td>{record.village}, {record.taluk}</td><td style={{ textAlign: 'right' }}>{area ? `${area} ac` : 'Not available'}</td><td>{calculated ? rate && area ? `${currency(rate)} / ac × ${area} ac` : 'Existing assessed amount used' : 'Click Calculate Compensation'}</td><td style={{ textAlign: 'right', fontWeight: 700 }}>{currency(assessed)}</td><td>{record.paymentStatus}</td></tr>; })}</tbody></table></div></div>
    <div className="gov-card" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16 }}><div><strong>Compensation Summary: {currency(total)}</strong><p style={{ marginTop: 4, fontSize: 12, color: 'var(--gov-slate-500)' }}>Paid: {currency(paid)} · Pending: {currency(Math.max(total - paid, 0))}. Calculations use existing assessed/rate data only and are not persisted.</p></div>{approved ? <span style={{ color: 'var(--gov-green-700)', fontWeight: 700 }}><CheckCircle2 size={16} /> Ready for District Officer</span> : <div style={{ display: 'flex', gap: 8 }}><button className="gov-btn gov-btn-secondary">Save Draft</button><button className="gov-btn gov-btn-primary" disabled={!calculated} onClick={() => setConfirming(true)}>Approve & Forward</button></div>}</div>
    <Modal isOpen={confirming} onClose={() => setConfirming(false)} title="Approve Compensation" subtitle="Frontend preview — no workflow status is persisted." footer={<><button className="gov-btn gov-btn-secondary" onClick={() => setConfirming(false)}>Cancel</button><button className="gov-btn gov-btn-primary" onClick={() => { setApproved(true); setConfirming(false); }}>Confirm & Forward</button></>}><p>Project: <strong>{activeProject.name}</strong></p><p>Affected landowners: <strong>{projectRecords.length}</strong></p><p>Total compensation: <strong>{currency(total)}</strong></p></Modal>
  </div>;
};
